# Cluster Name in VB
cluster_name: Kubernetes-Lab

network:
  vm-master01_ip: 10.10.0.60
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1

vms:
  master_vm: vm-master60
nodes:
  devops:
    cpu: 2
    memory: 12288

software:
  #box: bento/ubuntu-22.04
  box: debian/bookworm64

disks:
  dev_disk: 10
